version: '3.4'

services:
  reactfrontend:
    image: reactfrontend
    build:
      context: reactjs-demo
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
